name: Run Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: "Test library"
    runs-on: macos-12

    steps:
      - name: "Check out PR branch"
        uses: actions/checkout@v2

      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: "Run tests"
        run: ./gradlew test --console=plain
